spring:
  application:
    name: Personal_Project3

  datasource:
    url: jdbc:mysql://localhost:3306/project3_velog
    username: skdus
    password: skdus1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

server:
  port: 80